### ISSUE TITLE
Game Crashing when starting to ride Boat

### ISSUE THREAD

**Issue by YungZeiro** [happyredstone/sodiumplus#31] opened 2024-08-12 13:50 UTC
Hello,

me and friend noticed, that when you try to move in a boat, the game crashes. But only when you try to move it, sitting in it works.
Deactivating "Boat Item View Fabric" hotfixes it.

**Comment by NoSadBeHappy** [comment] 2024-08-12 16:30
Duplicate of https://github.com/happyredstone/sodiumplus/issues/30

**Comment by RedstoneWizard08** [comment] 2024-12-12 02:05
This seems to have been fixed

**Closed by RedstoneWizard08** 2024-12-12 02:05 UTC
